# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf6e8735c68c625ea1e3db35c696e280bb55b5be8f50f1a6e5e481fe8b4a5c162eb626062912b1ef03969e9a2a0d94312d4d1ce93c9201b77483f428093134f

test:
  secret_key_base: 2a0a7339366c298205fa92f1445d859e4288599614a0591dd3434d5e7362da824b5a43db8eb26020dd6c1a1c4a50ded3c4b07aff66538358c99b25baec64d659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
